#ifndef TARGET_HEADER_H
#define TARGET_HEADER_H

#define TARGET_DISPLAY_NAME "Galaxy A16 5G | Kernel 5.15.189"
#define TARGET_BUILD_NUMBER "A166MUBU8DZE9"

// Exact Samsung Galaxy A16 5G Exynos 1330 Offsets from symbols.txt
#define INIT_TASK_OFF 0x00b75be0ULL
#define RT_MUTEX_INIT_OFF 0x00bbec8ULL
#define RT_MUTEX_LOCK_OFF 0x00bb6acULL

#define SLIDE_TRACEFS_EVENT_ID 106
#define SLIDE_TRACEFS_WORKER_CALLER_OFF 0x000dbd9cULL
#define SLIDE_PSELECT_WORD_SHIFT 0

#endif // TARGET_HEADER_H
